language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy horlaitan15/reverseproxy
  - docker tag udagram-api-user horlaitan15/udagram-api-user
  - docker tag udagram-api-feed horlaitan15/udagram-api-feed
  - docker tag udagram-frontend horlaitan15/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push horlaitan15/reverseproxy
  - docker push horlaitan15/udagram-api-user
  - docker push horlaitan15/udagram-api-feed
  - docker push horlaitan15/udagram-frontend
