apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: horlaitan15/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 256m
          limits:
            cpu: 512m
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always












